# Copyright (C) 2018 DingYi <dingyi139@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_VERSION:=1.0
PKG_RELEASE:=68

LUCI_TITLE:=Netlink based bandwidth accounting
LUCI_DEPENDS:=+nlbwmon

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
